#docker-compose.yml
version: "3.8"

services:
  backend:
    image: health_backend                # local image name used during build
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: health_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/devops_db
    depends_on:
      - mongo
    # NOTE: removed host volume mounts for CI builds
    restart: unless-stopped

  frontend:
    image: health_frontend               # local image name used during build
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: health_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    # NOTE: removed host volume mounts for CI builds
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: health-db-ci
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=auth_db
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
